### PR TITLE
Update events.yml

### PR DESCRIPTION
**Pull request by kbrown599**
Time should be 1:30, not 17:30

### CODE REVIEW

**Comment by jmignault** [comment]
Editing events.yml won't fix the wrong time, because it's generated by a script. I am fixing the bug in the script, and once I do the listing will be fine.

**Comment by jmignault** [comment]
This is now fixed.

**Comment by kbrown599** [comment]
Thanks!!

-Sent from mobile.

**Comment by jmignault** [comment]
Thank you. This pull request led to fixing and clarifying a problem with the way we displayed the events that resulted in the times being shown in a human-readable way.

**Pull request closed without merging**
